### ISSUE TITLE
`to_upper/1` is not so obvious 

### ISSUE THREAD

**Issue by sobolevn** [sobolevn/recase#2]
`to_upper/1` could be misleading. Since upper case is `SOME-VALUE`.

I guess it should be renamed to `to_pascal/1`.

**Comment by princemaple** [comment]
Maybe don't reinvent the ones that's already in string module? i.e. simply leave out upper, lower, etc.

**Comment by sobolevn** [comment]
@princemaple thanks for the feedback!

My idea was to rename the existing `UpperCase` to `PascalCase` not to create confusion around it's name.

**Comment by princemaple** [comment]
Yep, I meant after that, no need to add it back.

**Comment by princemaple** [comment]
String module already got upper, lower and capital covered.
