### ISSUE TITLE
Recase logo offer

### ISSUE THREAD

**Issue by reallinfo** [sobolevn/recase#21]
Hello! I am a graphic designer. I contribute to open source software. I saw the logo in the Readme File. I wanted to customize the logo.  You can be sure I can do better. Do you want to see my new logo idea? 

I will wait for feedback. Have a nice day!

**Comment by sobolevn** [comment]
@reallinfo thanks for your offer! I really appreciate it.

But, I am used to this logo for this project.
I have a lot of other projects that need help:
- https://github.com/wemake-services/wemake-vue-template
- https://github.com/wemake-services/wemake-django-template
- https://github.com/sobolevn/dotfiles
- https://github.com/sobolevn/sobole-zsh-theme
- https://github.com/sobolevn/dump-env
- https://github.com/sobolevn/wakatime-zsh-plugin

Feel free to submit your ideas about any (or even all!) of these project.
I would absolutely love to see your work!

Cheers!

**Comment by reallinfo** [comment]
I designed such a logo for Recase. You do not have to use it. I just wanted to show it.  I will look at your other projects soon.

![recase](https://user-images.githubusercontent.com/36298335/40627633-bfc7f8ba-62c8-11e8-82bd-be43d66b53c8.jpg)

CHeers!

**Comment by sobolevn** [comment]
Nice! Looking forward to see more! 😎
