### ISSUE TITLE
Missing to_title function and TitleCase module

### ISSUE THREAD

**Issue by lustrousgorilla** [sobolevn/recase#51]
This is really baffling. Obviously I see both here on Github, but if add the `{:recase, "~> 0.4"}` dependency, fetch it with `mix deps.get`, and then go spelunking into the `deps/recase/...` directory both the function and module are missing. Is this some kind of hex bug?

**Comment by lustrousgorilla** [comment]
(fetching it directly from Github for now)

**Comment by sobolevn** [comment]
New release is coming! Sorry 🙂

**Comment by kidbombay** [comment]
Any ideas when?

**Comment by sobolevn** [comment]
Released. Sorry for the delay. https://hexdocs.pm/recase/0.5.0/readme.html
