### ISSUE TITLE
`to_camel` only capitalizes last word if given camel cased input

### ISSUE THREAD

**Issue by MrAlexLau** [sobolevn/recase#57]
`to_camel` produces unexpected output when given an existing camel case string. This seems to happen when the given string has more than 2 words in it:

```
Recase.to_camel("fooBar")
> "fooBar" # Correct

Recase.to_camel("fooBarBaz")
> "foobarBaz" # Incorrect, this should be "fooBarBaz"

Recase.to_camel("fooBarBazBiz")
> "foobarbazBiz" # Incorrect, this should be "fooBarBazBiz"
```

**Comment by sobolevn** [comment]
Yeap, that's a bug. Can you please help me with this one?

**Comment by MrAlexLau** [comment]
Actually, it looks like this was fixed in 0.4.0 and we were running 0.3.0! I could update the tests to have input that explicitly covers this if you'd like.

**Comment by sobolevn** [comment]
@MrAlexLau sounds awesome! Please, feel free 🙂

**Comment by sobolevn** [comment]
Closed by https://github.com/sobolevn/recase/pull/59
