### ISSUE TITLE
Are you interested by a PR about handling recase for Enumerable in a recursive way ?

### ISSUE THREAD

**Issue by elielhaouzi** [sobolevn/recase#62]
```
Recase.to_pascal(%{"camel_case" => 123, "PascalCase" => 456}) # %{"CamelCase" => 123, "PascalCase" => 456}
```

**Comment by elielhaouzi** [comment]
```
Recase.to_pascal(%{camel_case: "a", PascalCase: %{camel_case: "a"}) # %{"CamelCase" => "a", "PascalCase" => %{"CamelCase" => "a"}}
```

**Comment by sobolevn** [comment]
I am not really sure. I know that one can use it to fix the key cases in `json` or similar.
But, how hard it is to do manually?

**Comment by elielhaouzi** [comment]
I do a mistake about the examples. It will recase only the key but will
remain the value as is.

test "should pascal case key and value of a flat map" do
assert convert(%{"upper case" => "upper case"}) == %{"UpperCase" => "upper
case"}
end

How hard it is to do manually ? It is not very hard it is only 2 functions
that will handle the case when the value is a map or a list but it can be
helpfull if it is already in the lib.

def convert(map) when is_map(map) do
map
|> Enum.reduce(
%{},
fn {key, value}, acc ->
new_value =
case value do
value when is_binary(value) ->
value

_ ->
convert(value)
end

Map.put(acc, convert(key), new_value)
end
)
end

def convert(list) when is_list(list) do
list
|> Enum.map(&convert(&1))
end

**Comment by sobolevn** [comment]
We can make a helper in this case. And yes, we do not need to touch a value.
I will apreaciate a PR! Let's do something like: `Recase.Maps.covert()`

**Comment by elielhaouzi** [comment]
I do a mistake about the examples. It will recase only the key but will
remain the value as is.

```elixir
test "should pascal case key and value of a flat map" do
    assert convert(%{"upper case" => "upper case"}) == %{"UpperCase" => "upper case"}
end

test "should pascal case key and value of a nested map" do
    assert convert(%{"upper case" => %{"upper case" => "upper case"}}) == %{ "UpperCase" => % {"UpperCase" => "upper case"}}
end
```
How hard it is to do manually ? It is not very hard it is only 2 functions
that will handle the case when the value is a map or a list but it can be
helpfull if it is already in the lib.

```elixir
  def convert(map) when is_map(map) do
    map
    |> Enum.reduce(
      %{},
      fn {key, value}, acc ->
        new_value =
          case value do
            value when is_binary(value) ->
              value

            _ ->
              convert(value)
          end

        Map.put(acc, convert(key), new_value)
      end
    )
  end

  def convert(list) when is_list(list) do
    list
    |> Enum.map(&convert(&1))
  end
```

**Comment by sobolevn** [comment]
Or `Recase.Collections.convert_keys()`, since we can also work with lists. And `convert_keys` has more meaning.

**Comment by elielhaouzi** [comment]
> We can make a helper in this case. And yes, we do not need to touch a value.
> I will apreaciate a PR! Let's do something like: `Recase.Maps.covert()`

Ok great, so add it to utils ? what will be the interface from the recase.ex or the user will call directly `Recase.Maps.convert()`

**Comment by sobolevn** [comment]
Let's do a separate module, without a public interface. Since we only have  cases there. Do not want to mix things together.

**Comment by elielhaouzi** [comment]
I agree `convert_keys` is more declarative. we also need to know how to convert it.. what do you think about this `Recase.Collections.convert_keys(enumerable, :to_pascal)` `Recase.Collections.convert_keys(enumerable, :to_camel)`etc ?

it's a bit repetitive but I do not see a better way apart from doing a macro like you do in generic.ex

**Comment by sobolevn** [comment]
👍 

The other option is: `Recase.Collections.convert_keys(enumerable, &Recase.to_camel/1)`
You can decide which one fits best. It will be clear within the implementation.

**Comment by elielhaouzi** [comment]
your proposition is a lot better! I will do a PR! :)

**Comment by elielhaouzi** [comment]
Can you do a new release so I will use the Enumerable in my project ?

**Comment by sobolevn** [comment]
No problem, I will do that today! Thanks again!
